import { PlayBookState } from "pages/playbook/playbook.redux";
import { TrashState } from "pages/trash/trash.redux";
import { DashboardState } from "pages/user-dashboard/dashboard.redux";
import { AppState } from "src/app.model";
import { SearchState } from "src/layouts/admin/components/admin-header/header-auth.redux";
import { DataFilterStateType } from "src/layouts/admin/components/data-filter/data-filter.redux";
import { ActivityTrackerState } from "src/pages/activity-tracker/activity-tracker.redux";
import { adminSettingState } from "src/pages/admin-setting/settings-auth.redux";
import { AlertsState } from "src/pages/alerts/alerts.redux";
import { AuthState } from "src/pages/auth/auth.model";
import { CommentBoxStateType } from "src/pages/comment/comment-box.redux";
import { DashboardContractState } from "src/pages/contract-data-list/contract-data-list.redux";
import { ContractStateType } from "src/pages/contract/contract.redux";
import { DashboardStatsState } from "src/pages/dashboard-stats/dashboard-stats.redux";
import { GRCDashboardStateType } from "src/pages/grc-dashboard/grc-dashboard.redux";
import { ManageMembersState } from "src/pages/manage-members/manage-members.redux";
import { TeamsFilesFoldersState } from "src/pages/manage-team/team-files/team-files.redux";
import { TeamStateType } from "src/pages/manage-team/team.redux";
import { OnlyOfficeStateType } from "src/pages/pre-contract/contract-editor/only-office-editor/onlyoffice.redux";
import { PreContractStateType } from "src/pages/pre-contract/pre-contract.redux";
import { contractApprovalStateType } from "src/pages/pre-contract/right-section-preContract/approval-component/approval.redux";
import { CollaborationStateType } from "src/pages/pre-contract/right-section-preContract/collaboration-component/collaboration.redux";
import { DocusignStateType } from "src/pages/pre-contract/signature-precontract/docusign.redux";
import { MyDraftState } from "src/pages/pre-dashboard/drafts/drafts.redux";
import { TemplatesState } from "src/pages/pre-dashboard/templates/templates.redux";

export interface RootState {
  auth: AuthState;
  dashboard: DashboardState;
  app: AppState;
  contract: ContractStateType;
  commentBox: CommentBoxStateType;
  headerSearchContract: SearchState;
  dashboardContract: DashboardContractState;
  alerts: AlertsState;
  team: TeamStateType;
  manageMembers: ManageMembersState;
  activityTracker: ActivityTrackerState;
  teamDashboard: TeamsFilesFoldersState;
  adminSettingContract: adminSettingState;
  trash: TrashState;
  dashboardStats: DashboardStatsState;
  templates: TemplatesState;
  drafts: MyDraftState;
  preContract: PreContractStateType;
  contractApprovals: contractApprovalStateType;
  collaboration: CollaborationStateType;
  docusign: DocusignStateType;
  onlyOfficeEditor: OnlyOfficeStateType;
  grcDashboard: GRCDashboardStateType;
  playbook: PlayBookState;
  dataFilter: DataFilterStateType;
}
